# Generated by Django 3.1.3 on 2020-11-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_image_url',
        ),
    ]
