# Generated by Django 3.1.3 on 2020-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
