# Generated by Django 3.1.3 on 2020-11-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201118_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(null=True),
        ),
    ]
