# Generated by Django 3.1.3 on 2020-11-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('ootd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ootd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='like',
            name='ootd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootd.ootd'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='follow',
            name='followee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follwer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ootd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootd.ootd'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='ootd.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
