# Generated by Django 3.1.3 on 2020-11-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootd', '0002_auto_20201120_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follwer',
            new_name='follower',
        ),
    ]
