# Generated by Django 3.1.3 on 2020-11-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootd', '0002_auto_20201126_2109'),
        ('ootd', '0002_auto_20201126_1706'),
    ]

    operations = [
    ]
