# Generated by Django 3.1.3 on 2020-11-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootd', '0003_auto_20201120_1330'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
    ]
