# Generated by Django 3.1.3 on 2020-11-18 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ootd', '0003_auto_20201118_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ootd',
            name='image_url',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follows',
        ),
        migrations.CreateModel(
            name='OotdImageUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('ootd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootd.ootd')),
            ],
            options={
                'db_table': 'ootd_image_urls',
            },
        ),
    ]
