# Generated by Django 3.1.3 on 2020-11-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootd', '0004_auto_20201118_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
