# Generated by Django 3.1.3 on 2020-11-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ootd', '0005_auto_20201118_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follwer',
            new_name='follower',
        ),
    ]
