# Generated by Django 3.1.3 on 2020-11-21 07:09
# Generated by Django 3.1.3 on 2020-11-20 03:41
# Generated by Django 3.1.3 on 2020-11-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discount_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('limit_period', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.coupon')),
            ],
            options={
                'db_table': 'users_coupons',
            },
        ),
    ]
