# Generated by Django 3.1.3 on 2020-11-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201118_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit_period',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
