# Generated by Django 3.1.3 on 2020-11-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201118_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
