# Generated by Django 3.1.3 on 2020-11-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('ootd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('nickname', models.CharField(max_length=20)),
                ('profile_image_url', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('website_url', models.URLField(null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('coupon', models.ManyToManyField(through='cart.UserCoupon', to='cart.Coupon')),
                ('follow', models.ManyToManyField(null=True, related_name='_user_follow_+', through='ootd.Follow', to='user.User')),
                ('like', models.ManyToManyField(null=True, related_name='like_user', through='ootd.Like', to='ootd.Ootd')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
