# Generated by Django 3.1.3 on 2020-11-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='genders',
        ),
    ]
