# Generated by Django 3.1.3 on 2020-11-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='like',
            new_name='ootd_like',
        ),
    ]
