# Generated by Django 3.1.2 on 2020-11-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20201118_1136'),
        ('product', '0002_remove_product_cart'),
        ('ootd', '0003_auto_20201118_1118'),
        ('user', '0002_auto_20201118_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(through='cart.Cart', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='_user_follow_+', through='ootd.Follow', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ootd_like',
            field=models.ManyToManyField(related_name='like_user', through='ootd.Like', to='ootd.Ootd'),
        ),
    ]
